create DATABASE DB_POWERBI

create TABLE CLIENTE(
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    SOBRENOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
)

INSERT INTO CLIENTE (NOME,SOBRENOME,EMAIL)
VALUES ('JOAO', 'VITOR', 'JOAO@GMAIL'),
       ('BRUNO','OLIVEIRA','BRUNO@GMAIL'),
       ('VALÉRIA','CRISTINA', 'VALERIA@GMAIL')

INSERT INTO CLIENTE (NOME,SOBRENOME,EMAIL)
VALUES ('CARLOS', 'PEREIRA', 'CARLOS@GMAIL')
       

       SELECT * FROM CLIENTE

CREATE TABLE PEDIDOS (
    ID SERIAL PRIMARY KEY,
    ID_CLIENTE INT,
    DATA_PEDIDO DATE NOT NULL,
    TOTAL NUMERIC(6,0),
    STATUS TEXT CHECK(STATUS IN ('EM ANDAMENTO','FINALIZADO','CANCELADO')),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
)
ALTER TABLE PEDIDOS
  ALTER COLUMN STATUS SET DEFAULT 'EM ANDAMENTO' 

INSERT INTO PEDIDOS(ID_CLIENTE,DATA_PEDIDO,TOTAL)
VALUES (1,'2024-04-01',50),
(2,'2024-04-02',75),
(1,'2024-04-03',120),
(3,'2024-04-04',35),
(1,'2024-04-05',90);

SELECT * FROM PEDIDOS